# SPDX-FileCopyrightText: 2024 Dennis Gläser <dennis.a.glaeser@gmail.com>
# SPDX-License-Identifier: MIT

name: prepare-environment
runs:
  using: composite
  steps:
    - name: install-dependencies
      run: |
        sudo apt install cmake python3 python3-dev python3-pip python3-venv
      shell: bash

    - name: create-venv
      run: |
        python3 -m venv cpplot_venv
        source cpplot_venv/bin/activate
        python3 -m pip install matplotlib
        echo "PATH=$(pwd)/cpplot_venv/bin:$PATH" >> "$GITHUB_ENV"
      shell: bash
