name: test-suite

on:
  push:
    branches: [main]
  pull_request:
    branches:
    - main
    - 'releases/**'
  schedule:
    - cron: '30 22 * * 0,3'
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout-repository
        uses: actions/checkout@v2

      # install of make can be omitted once the container provides it per default
      - name: build-tests
        run: |
          cmake -B build
          cmake --build build

      - name: run-tests
        run: cd build && ctest --output-on-failure

  test-as-submodule:
    runs-on: ubuntu-22.04
    steps:
      - name: install-dependencies
        run: |
          apt install cmake python3 python3-dev python3-pip
          python3 -m pip install matplotlib

      - name: checkout-repository
        uses: actions/checkout@v2

      - name: move-to-sub-directory
        run: mv * cpplot/ 2> /dev/null

      - name: move-out-test-directory
        run: mv cpplot/test .

      - name: generate-cmake-lists
        run: |
          echo "cmake_minimum_required(VERSION 3.18)" > CMakeLists.txt
          echo "project(cpplot_submodule_test)" >> CMakeLists.txt
          echo "set(CPPLOT_INCLUDE_TESTS OFF)" >> CMakeLists.txt
          echo "add_subdirectory(cpplot)" >> CMakeLists.txt
          echo "enable_testing()" >> CMakeLists.txt
          echo "add_subdirectory(test)" >> CMakeLists.txt

      # install of make can be omitted once the container provides it per default
      - name: build-tests
        run: |
          cmake -B build
          cmake --build build

      - name: run-tests
        run: cd build && ctest --output-on-failure
